[package]
name = "sframe-io"
version = "0.1.0"
edition = "2021"

[dependencies]
sframe-types = { path = "../sframe-types" }
sframe-config = { path = "../sframe-config" }
ureq = { version = "3", optional = true }

[features]
default = []
http = ["ureq"]

[dev-dependencies]
tempfile = "3"
